import styles from "../styles/Notes.module.css";
import Head from "next/head";
import Image from "next/image";
import Note from '../components/Note'
import {ENDPOINT} from "../utils/constants";

const Notes = ({notes}) => {
    return <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>

        <main className={styles.main}>
            <h1 className={styles.title}>Notes</h1>
            {
                notes && notes.map(note => <Note key={note.id} note={note}/>)
            }

        </main>

        <footer className={styles.footer}>
            <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
            >
                Powered by{' '}
                <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
            </a>
        </footer>
    </div>

}

export async function getServerSideProps() {
    const notes = await ((await fetch(`${ENDPOINT}/api/notes`)).json())
    return {
        props: {notes},
    }
}

export default Notes